export default {
    EMAIL_USER_ID: process.env.REACT_APP_EMAIL_USER_ID,
    EMAIL_TEMPLATE_ID: process.env.REACT_APP_EMAIL_TEMPLATE_ID,
    EMAIL_ACCESS_TOKEN: process.env.REACT_APP_EMAIL_ACCESS_TOKEN,
    EMAIL_SERVICE_ID: process.env.REACT_APP_EMAIL_SERVICE_ID,
}